# Dieses Repo ist Teil des Heimgewebes.
# Systemweiter Kontext durch Heimgeist:
#   metarepo/ai-contexts/heimgeist.ai-context.yml

system_context:
  heimgeist: "../metarepo/ai-contexts/heimgeist.ai-context.yml"

ai_context_version: 1.0

project:
  name: mitschreiber
  summary: On-device context sampler & embedder (Rust/Python).
  role: producer_structured_notes
  primary_language: Rust/Python
  visibility: internal

dependencies:
  internal:
    - name: contracts
      relationship: uses
      interface:
        - jsonl_line_schema
    - name: chronik
      relationship: uses
      interface:
        - http_ingest_optional
  external:
    - name: jq

architecture:
  entrypoints:
    - mitschreiber (Python CLI)
  key_paths:
    - path: src/lib.rs
      purpose: Python/Rust FFI entrypoint
    - path: mitschreiber/cli.py
      purpose: CLI entrypoint
  data_flow:
    input: user/agent inputs
    processing: normalize → validate
    output: append *.jsonl

conventions:
  branching: "main, feature/*"
  commit_prefix: "mitschreiber"
  ci_platform: github_actions

documentation:
  runbook: docs/runbook.md

ai_guidance:
  do:
    - ensure each JSONL line is standalone valid JSON
  dont:
    - write partial lines or multi-line JSON
