# Dieses Repo ist Teil des Heimgewebes.
# Systemweiter Kontext durch Heimgeist:
#   metarepo/ai-contexts/heimgeist.ai-context.yml

system_context:
  heimgeist: "../metarepo/ai-contexts/heimgeist.ai-context.yml"

ai_context_version: 1.1

project:
  name: mitschreiber
  summary: On-device context sampler & embedder (Rust/Python).
  role: producer_structured_notes
  primary_language: Rust/Python
  visibility: internal

heimgewebe:
  axis:
    - Events
    - Semantik
    - Motorik
  fleet:
    enabled: true
  wgx:
    profile_expected: true
    guard_smoke_expected: true

interfaces:
  consumes:
    - "x11.events"
    - "user.input"
  produces:
    - "event.line"
    - "export/*.jsonl"

contracts:
  schemas:
    - path: "contracts/*.schema.json"
      note: "Reference canonical schemas; do not fork lightly."

dependencies:
  internal:
    - name: contracts
      relationship: uses
      interface:
        - jsonl_line_schema
    - name: chronik
      relationship: uses
      interface:
        - http_ingest_optional
  external:
    - name: jq
    - name: bash
      version: ">=4"

architecture:
  entrypoints:
    - mitschreiber (Python CLI)
  key_paths:
    - path: src/lib.rs
      purpose: Python/Rust FFI entrypoint
    - path: mitschreiber/cli.py
      purpose: CLI entrypoint
  data_flow:
    input: user/agent inputs
    processing: normalize → validate
    output: append *.jsonl

boundaries:
  not_responsible_for:
    - "Doing network ingest without aussensensor"
    - "Permanently storing data beyond local retention"
  dangerous_assumptions:
    - "Assume repo is Fleet-enabled without checking .wgx/"
    - "Assume X11 is always available (must handle headless)"

conventions:
  branching: "main, feature/*"
  commit_prefix: "mitschreiber"
  ci_platform: github_actions

documentation:
  runbook: docs/runbook.md

ai_guidance:
  do:
    - ensure each JSONL line is standalone valid JSON
  dont:
    - write partial lines or multi-line JSON
