name: Validate JSONL
on:
  push:
    branches: [ main ]
  pull_request:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-state:
    uses: heimgewebe/metarepo/.github/workflows/reusable-validate-jsonl.yml@contracts-v1
    with:
      jsonl_paths_list: |
        fixtures/mitschreiber/*.jsonl
      schema_url: https://raw.githubusercontent.com/heimgewebe/metarepo/contracts-v1/contracts/os.context.state.schema.json

  # Beispiel für weitere Streams (später aktivieren):
  # validate-embed:
  #   uses: heimgewebe/metarepo/.github/workflows/reusable-validate-jsonl.yml@contracts-v1
  #   with:
  #     jsonl_paths_list: fixtures/mitschreiber/embed*.jsonl
  #     schema_url: https://raw.githubusercontent.com/heimgewebe/metarepo/contracts-v1/contracts/os.context.text.embed.schema.json
